### ISSUE TITLE
Implementacion de una opción para saltarse el blacklisting de Mojang

### ISSUE THREAD

**Issue by jaime29010** [DarkLBP/Krothium-Launcher#1]
Referencia: https://github.com/SquidHQ/launcher
Lo que hace SquidHQ es simplemente saltarse Netty cuando se descargan las dependencias.

**Comment by DarkLBP** [comment]
@jaime29010 que blacklist afecta al launcher? El único que he visto es el de los skins y pero ya lo salta.

**Comment by jaime29010** [comment]
Cuando un servidor no sigue la EULA, Mojang lo puede bloquear para que el cliente no se pueda conectar al servidor.

**Comment by DarkLBP** [comment]
@jaime29010 Corregido en https://github.com/DarkLBP/Krothium-Launcher/commit/02d39b4aaeb8e3fa373b28af40a758a9c0616f72
