### ISSUE TITLE
Add a Preloader.

### ISSUE THREAD

**Issue by TryHardDood** [DarkLBP/Krothium-Launcher#20]
Sometimes it hard to notice if the launcher is running (because it loads a website and if I have slow internet then it would hang for a while) 

Preloader: 
* https://docs.oracle.com/javase/8/javafx/api/javafx/application/Preloader.html
* https://blog.codecentric.de/en/2015/09/javafx-how-to-easily-implement-application-preloader-2/

**Comment by DarkLBP** [comment]
You mean to show a splash screen with the logo or something while is loading?

**Comment by TryHardDood** [comment]
Yes, something like that.
Just indicate that the launcher is running.

**Comment by DarkLBP** [comment]
Added on https://github.com/DarkLBP/Krothium-Launcher/commit/be5c9b387fbeecfe3e136bd1c7915cccff468035
