### ISSUE TITLE
Las listas se quedan abiertas

### ISSUE THREAD

**Issue by Truebamateo** [DarkLBP/Krothium-Launcher#23]
Algunas listas del launcher, ya sea la de seleccionar un perfil, o cambiar el icono del perfil, o la de seleccionar un idioma, etc) se quedan abiertas cuando no se pasa el mouse sobre ellas.
Ejemplo:
![bug](https://user-images.githubusercontent.com/32852493/37536618-e0d82daa-2929-11e8-88ea-e9b3f0d61eae.png)

**Comment by DarkLBP** [comment]
Ya debería estar solucionado en el commit https://github.com/DarkLBP/Krothium-Launcher/commit/eba3eccdc66a733119f003aa4dc29b190c69b767
