### ISSUE TITLE
Problema con el tamaño del contenedor de noticias

### ISSUE THREAD

**Issue by Truebamateo** [DarkLBP/Krothium-Launcher#25]
El contenedor de noticias no cambia su tamaño siempre que el launcher se redimensiona, específicamente cuando el launcher está maximizado y cambia su tamaño ya sea haciendo click nuevamente en el botón maximizar o doble click en la barra de título, o arrastrando la barra de título.
![bug](https://user-images.githubusercontent.com/32852493/37665722-a7dc4930-2c3c-11e8-8fc8-322f84a6645e.png)

**Comment by DarkLBP** [comment]
Al parecer es un bug de JavaFX en Java 8, al menos en Java 9 funciona bien. He empleado otra forma de mantener el tamaño de forma manual y ya parece que funciona bien.
