### ISSUE TITLE
Algunos bugs y sugerencias

### ISSUE THREAD

**Issue by Truebamateo** [DarkLBP/Krothium-Launcher#27]
Cuando el juego está abierto y el launcher sigue visible debido a que está activada la opción de mantener el launcher visible mientras se ejecuta el juego, algunos interruptores funcionan pero no cambian su posición.
Esos interruptores son los que se encuentran en las opciones de un perfil, y el bug solo ocurre con interruptores activados.

Interruptores activados:
![interruptoreson](https://user-images.githubusercontent.com/32852493/39199225-4f975730-47bf-11e8-817d-0db5c7713616.png)

Interruptores desactivados (siguen apareciendo como si estuvieran activados):
![interruptoresoff](https://user-images.githubusercontent.com/32852493/39199239-58234210-47bf-11e8-9291-94a00f65f2bb.png)

Mientras escribía algunas sugerencias que coloqué más abajo, encontré otro bug, aunque no estoy seguro del todo si es un bug o es algo intencional. Cuando se crea o guarda un perfil, a la hora de crear un nuevo perfil y no tocar el icono (dejar el que viene por defecto), cuando se guarde el perfil contendrá el icono del último perfil creado o guardado.

Otro bug es que el launcher no me detecta correctamente el sistema operativo; tengo Windows 10 actualizado (Fall Creators Update) y en los logs dice que tengo Windows 8.1

# **Sugerencias:**
Creo que no estaría mal un botón para duplicar el perfil seleccionado.

Y cuando se crea un nuevo perfil y no se pone ningún nombre, a la hora de editarlo/crearlo en el nombre aparece como si se llamaría Mi configuración pero se guarda como Perfil sin nombre.

![nombre](https://user-images.githubusercontent.com/32852493/39199507-041c04d0-47c0-11e8-84d1-ffd035a1c819.png)

![sinnombre](https://user-images.githubusercontent.com/32852493/39199554-21a052a4-47c0-11e8-8635-7fb68ae91c9b.png)

También estaría bien una opción en Ajustes que haga que el launcher se abra cuando el juego se cierre.

**Comment by Truebamateo** [comment]
Y el launcher no me detecta correctamente el sistema operativo; tengo Windows 10 actualizado (Fall Creators Update) y en los logs dice que tengo Windows 8.1

**Comment by DarkLBP** [comment]
El bug de los botones y del icono han sido corregido. El bug de Windows es de Java y no del launcher por lo que no puedo hacer gran cosa a menos que encuentre una forma mas fiable de obtener el sistema operativo.
Las sugerencias las tendre en cuenta para la próxima version grande con contenido del launcher.
Lo de Mi configuración no es el nombre del perfil es como una sugerencia para el nombre.
