### ISSUE TITLE
El launcher deja de responder

### ISSUE THREAD

**Issue by Truebamateo** [DarkLBP/Krothium-Launcher#28]
Cuando no hay conexión a internet y el launcher está en el modo offline, en el apartado skins si se cambia el modelo del jugador, por ejemplo de clásico a delgado y luego de nuevo a clásico, el launcher deja de responder.

**Comment by Truebamateo** [comment]
Y volví a causar ese error, cerré el launcher y lo volví a abrir, y el bootstrap mostró el mensaje Failed to start the launcher, y en los logs no indica ningún error más que el que no se encuentra mc.krothium.com, y el launcher inició igual.
Creo que el boostrap solo genera su log al cerrar el launcher. Esto puede ser el motivo de que algunas personas en el foro cuando exportan los registros, el del bootstrap no tiene nada.

**Comment by ascezero13** [comment]
Time to upgrade my Minecraft to premium https://freeminecraftgiftcode.net

**Comment by TBM13** [comment]
@ascezero13 I already have premium, and i don't play Minecraft anymore.
