### ISSUE TITLE
Krothium Server Side Open Source?

### ISSUE THREAD

**Issue by GabrielAugustoTI** [DarkLBP/Krothium-Launcher#4]
You can make server side open source?
https://mc.krothium.com/authenticate
https://mc.krothium.com/refresh
https://mc.krothium.com/validate
etc...
You can? I need to login with my server forum credentials...

**Comment by GabrielAugustoTI** [comment]
@DarkLBP

**Comment by DarkLBP** [comment]
For security reasons and the high costs of making it, the server side script won't be open source.

**Comment by GabrielAugustoTI** [comment]
But... i need custom registration and login for my server! Please...

**Comment by GabrielAugustoTI** [comment]
Just add a way to start the game without authentication.. pls
